<?php


namespace frontend\commands;


use dektrium\user\models\LoginForm;
use frontend\models\telegram\Action;
use Yii;

class Signin extends Action
{

//    public static function run($command, callable $fun)
//    {
//        $data = json_decode(file_get_contents("php://input"));
//        $telegram = Yii::$app->telegram;
//        $action = Action::findOne(["chat_id" => ($telegram->input->message) ? $telegram->input->message->from->id : $data["callback_query"]["from"]["id"]]);
//        $message = ($telegram->input->message) ? $telegram->input->message : $data["callback_query"];
//        if ($action) {
//            $telegram->sendMessage([
//                "chat_id" => ($telegram->input->message) ? $telegram->input->message->from->id : $data["callback_query"]["from"]["id"],
//                "text" => "Input your login",
//            ]);
//            (new Action(["chat_id" => ($telegram->input->message) ? $telegram->input->message->from->id : $data["callback_query"]["from"]["id"], ["action_name" => self::class]]))->save();
//            return parent::run($command, $fun); // TODO: Change the autogenerated stub
//        } elseif ($action->args === null) {
//            $action->args = ["login" => $message->text];
//            if ($action->save()) {
//                $telegram->sendMessage([
//                    "chat_id" => ($telegram->input->message) ? $telegram->input->message->from->id : $data["callback_query"]["from"]["id"],
//                    "text" => "Input your password",
//                ]);
//            }
//        } else {
//            $loginForm = Yii::createObject(LoginForm::className());
//            $loginForm->login = $action->args["login"];
//            $loginForm->password = $message->text;
//            Yii::error($loginForm);
//            if ($loginForm->login()) {
//                Yii::$app->user->identity->profile->telegram_chat_id = $telegram->input->message->from->id;
//                Yii::$app->user->identity->profile->save();
//                $action->delete();
//                $telegram->sendMessage([
//                    "chat_id" => $message->from->id,
//                    "text" => "You are logged"
//                ]);
//                return Start::run($command, $fun);
//            }
//        }
//    }
}