<?php


namespace frontend\models\telegram;


class TelegramForm extends \yii\base\Model
{

    public function load($data, $formName = null)
    {
        return parent::load($data, $formName); // TODO: Change the autogenerated stub
    }
}